# Generated by Django 4.0.3 on 2022-04-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='referencia',
            new_name='referencias',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(default='AA', max_length=2),
        ),
    ]
